<?php

namespace FacturationBundle\Repository;

/**
 * CategPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
