<?php

namespace FacturationBundle\Repository;

/**
 * FacturePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturePrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
